<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net35;netstandard2.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<RootNamespace>SAL.Interface.Caching</RootNamespace>
		<Deterministic>false</Deterministic>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
		<NoWarn>CA1416</NoWarn>
		<DefineConstants>WIN</DefineConstants>
	</PropertyGroup>

	<!--nuspec-->
	<PropertyGroup>
		<PackageId>SAL.Interface.Caching</PackageId>
		<Version>$(Version)</Version>
		<Title>Base SAL interfaces for caching plugins</Title>
		<Description>Base interfaces for caching logic used inside SAL plugins.</Description>
		<Authors>Danila Korablin</Authors>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>docs\README.md</PackageReadmeFile>
		<PackageIcon>docs\SAL.100.png</PackageIcon>
		<RepositoryUrl>https://github.com/DKorablin/SAL.Interface.Caching</RepositoryUrl>
		<PackageTags>SAL;plugin;Cache;Interface</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\docs" />
		<None Include="..\Images.Shared\SAL.100.png" Pack="true" PackagePath="\docs" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<Optimize>true</Optimize>
		<PublishSingleFile>true</PublishSingleFile>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="'$(GenerateDocumentationFile)' == 'False'">
		<!--This Hack is added to change output folder for local builds because Directory.Build.props file is maintained centrally using shared project-->
		<OutputPath>$(SolutionDir)..\..\bin\$(SolutionName)</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttributes Include="AssemblyMetadata" Condition="'$(TargetFramework)'=='netstandard2.0'">
			<_Parameter1>ProjectUrl</_Parameter1>
			<_Parameter2>https://github.com/DKorablin/SAL.Interface.Caching</_Parameter2>
		</AssemblyAttributes>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SAL.Flatbed">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>